apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: saniolsida/my-spring-app:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "2.5Gi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/myappdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: db-secret

            # 2. Redis 연결 (redis-service 사용)
            - name: SPRING_DATA_REDIS_HOST
              value: "redis-service"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"

            # 3. Kafka 연결 (kafka-service 사용)
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            # 프로듀서 설정도 확실히 강제 주입
            - name: SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
spec:
  type: LoadBalancer # 외부(내 브라우저)에서 접속 가능하게 설정
  selector:
    app: spring-app
  ports:
    - protocol: TCP
      port: 8080      # 외부 노출 포트
      targetPort: 8080 # 컨테이너 내부 포트